import {
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  FETCH_CAT_FAILURE,
  ADOPT_CAT_REQUEST,  
  ADOPT_CAT_FAILURE
} from './cat';

import {
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_FAILURE,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_FAILURE
} from './dog';

const actions = {    
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  FETCH_CAT_FAILURE,
  ADOPT_CAT_REQUEST, 
  ADOPT_CAT_FAILURE,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_FAILURE,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_FAILURE
}
export default actions;